services:
  app:
    image: node:18-alpine
    container_name: next-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install -force && npm run dev:staging"
    environment:
      - NODE_ENV=development
