version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
